### ISSUE TITLE
Unnecessary mut?

### ISSUE THREAD

**Issue by ids1024** [servo/rust-fontconfig#32]
Looking at `FcPatternAddString`, the second and third argument use `*mut`, while the fontconfig documentation defines them as `const` (this presumably also applies to many other functions).

I'm not too familiar with Rust's FFI, but shouldn't those be `*const`? If so, I can fix these and submit a PR.

**Comment by jdm** [comment]
Yep, *const would be more appropriate here. Fixing that would be great!
