### ISSUE TITLE
/usr/bin/file: No such file or directory

### ISSUE THREAD

**Issue by kvark** [servo/rust-fontconfig#41]
Failure building https://github.com/lapce/lapce on NixOS:

>  /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/configure: line 7528: /usr/bin/file: No such file or directory

Is it necessary to refer to `/usr/bin/file` like this? Can it be assumed in PATH instead?

**Comment by jdm** [comment]
This is https://github.com/servo/fontconfig/issues/10.
