### ISSUE TITLE
Clarify copyright holders

### ISSUE THREAD

**Issue by jamessan** [servo/rust-fontconfig#42]
`LICENSE-MIT` states the copyright is held by `Mozilla Foundation`, but `src/*.rs` says it's held by `The Servo Project Developers`.  `COPYRIGHT` doesn't mention anyone.  Could this please be clarified?

**Comment by sylvestre** [comment]
Context for other: @jamessan is trying to get this crate in Debian and the person in charge of the license check was confused.

When the work on rust-fontconfig was happening, it was under the Mozilla umbrella. 
The Servo project, back then, was a Mozilla project (now under the Linux Foundation) and didn't have (afaik) a separate entity.

So, it is pretty much the same.

@SimonSapin (salut!) 
I created this PR https://github.com/servo/rust-fontconfig/pull/43

**Comment by jamessan** [comment]
Addressed by #43
