### ISSUE TITLE
lib name conflict with yeslogic/fontconfig-rs

### ISSUE THREAD

**Issue by jgarnierGit** [servo/rust-fontconfig#44]
Hi there,

I have recently identified a lib name conflict between this crate and https://github.com/yeslogic/fontconfig-rs,

I opened a thread here https://users.rust-lang.org/t/dependencies-links-resolver-conflict/87801/4
to illustrate a cohabitation incompatibilities between 2 major crates in their domain.

In my opinion, the solution of less effort would be to synchronize with the other lib to rename one or the other and remove the conflict.

What do you think of that solution ?

Resolving this conflict can improve a lot the Rust crates ecosystem, I have opened a similar issue on the yeslogic/fontconfig-rs
=> https://github.com/yeslogic/fontconfig-rs/issues/33
Open to discussion :)
Kind regards

**Comment by Manishearth** [comment]
This isn't an issue with the crate names here; this is an issue with native linkage; only one crate can produce a _native_ library of a given name, and these are both crates that wrap around the same native library (fontconfig)

**Comment by jgarnierGit** [comment]
Thanks for your answer
